import { Platform, StyleSheet } from "react-native";
import { radii, ThemeColors } from "../lib/theme";

export function createModalStyles(colors: ThemeColors) {
  return StyleSheet.create({
    sheetRoot: { flex: 1 },
    body: { flex: 1 },
  });
}

export function createLibraryStyles(colors: ThemeColors) {
  return StyleSheet.create({
    libraryRoot: {
      flex: 1,
      width: "100%",
      alignSelf: "stretch",
    },
    librarySectionContent: {
      marginTop: 10,
    },
    librarySearchShell: {
      marginBottom: 6,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
    },
    librarySearchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 11,
      paddingVertical: 6,
      minHeight: 36,
    },
    librarySearchDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginHorizontal: 14,
    },
    searchInput: { flex: 1, color: colors.inputText, fontSize: 14, lineHeight: 18, padding: 0 },
    searchActionBtn: {
      width: 28,
      height: 28,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radii.pill,
    },
    searchActionBtnActive: {
      backgroundColor: colors.primaryGlow,
    },
    searchActionBtnPressed: { opacity: 0.72 },
    linkDownloadError: {
      color: colors.error,
      fontSize: 12,
      lineHeight: 16,
      marginTop: -2,
      marginBottom: 6,
      paddingHorizontal: 4,
    },
    errorWrap: { paddingHorizontal: 16, marginBottom: 8 },
    sectionSpinner: { marginVertical: 6, alignSelf: "center" },
    platformGroupSpaced: { marginTop: 6 },
    hubBanner: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      padding: 12,
      marginBottom: 12,
      borderRadius: radii.md,
      backgroundColor: colors.primaryGlow,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
    },
    hubBannerBody: { flex: 1, minWidth: 0 },
    hubBannerTitle: {
      color: colors.primaryLight,
      fontSize: 13,
      fontWeight: "700",
      marginBottom: 4,
    },
    hubBannerText: { color: colors.textMuted, fontSize: 14, lineHeight: 20 },
    pcConsentBanner: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      padding: 12,
      marginBottom: 10,
      borderRadius: radii.md,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    pcConsentBannerBody: { flex: 1, minWidth: 0 },
    pcConsentBannerTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
      marginBottom: 4,
    },
    pcConsentBannerText: { color: colors.textMuted, fontSize: 13, lineHeight: 18 },
    hubBannerLink: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginTop: 8,
      alignSelf: "flex-start",
    },
    hubBannerLinkPressed: { opacity: 0.65 },
    hubBannerLinkText: {
      color: colors.primaryLight,
      fontSize: 13,
      fontWeight: "600",
    },
    libraryBlockWrap: {
      paddingHorizontal: 16,
      marginBottom: 10,
    },
    libraryBlockBanner: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      padding: 12,
      borderRadius: radii.md,
      borderWidth: 1,
    },
    libraryBlockBannerWarning: {
      backgroundColor: "rgba(245,158,11,0.08)",
      borderColor: "rgba(245,158,11,0.28)",
    },
    libraryBlockBannerError: {
      backgroundColor: colors.errorBg,
      borderColor: colors.errorBorder,
    },
    libraryBlockTitle: {
      fontSize: 13,
      fontWeight: "700",
      marginBottom: 4,
    },
    libraryBlockHint: {
      color: colors.textDim,
      fontSize: 12,
      lineHeight: 17,
      marginTop: 6,
    },
    libraryRowWrap: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    libraryRowError: {
      marginTop: -4,
      marginBottom: 6,
      marginHorizontal: 0,
    },
    libraryRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 10,
    },
    libraryRowPressed: { opacity: 0.82 },
    serverCirclesRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginTop: 8,
      marginBottom: 12,
    },
    serverHalf: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 8,
      gap: 12,
    },
    serverHalfPressed: { opacity: 0.65 },
    serverCircle: {
      width: 128,
      height: 128,
      borderRadius: 64,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primaryGlow,
      borderWidth: 2,
      borderColor: colors.primaryBorder,
    },
    serverCircleEmpty: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    serverTextWrap: { alignItems: "center", gap: 2, paddingHorizontal: 8 },
    serverModelName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "700",
      textAlign: "center",
    },
    serverLabel: {
      color: colors.textMuted,
      fontSize: 12,
      textAlign: "center",
    },
    libraryCard: {
      flexDirection: "column",
      gap: 10,
      paddingVertical: 14,
    },
    libraryCardLeft: { alignItems: "flex-start" },
    libraryCardRight: { alignItems: "flex-end" },
    libraryCardIcon: {
      width: 56,
      height: 56,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    libraryCardBody: { width: "100%", minWidth: 0 },
    libraryCardBodyRight: { alignItems: "flex-end" },
    libraryIcon: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      position: "relative",
    },
    libraryBody: { flex: 1, minWidth: 0 },
    libraryTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: 6,
      marginBottom: 4,
    },
    libraryName: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "600",
      lineHeight: 21,
      flexShrink: 1,
    },
    libraryNameLoaded: {
      color: colors.primaryLight,
    },
    libraryStatsLoaded: {
      color: colors.primaryLight,
    },
    libraryModelId: {
      color: colors.textDim,
      fontSize: 12,
      lineHeight: 16,
      fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
      marginTop: 2,
    },
    libraryStats: { color: colors.textMuted, fontSize: 11, lineHeight: 15 },
    libraryDesc: { color: colors.textDim, fontSize: 13, lineHeight: 18, marginTop: 4 },
    progressTrack: {
      height: 4,
      backgroundColor: colors.borderStrong,
      borderRadius: 2,
      marginTop: 6,
      overflow: "hidden",
      flex: 1,
      minWidth: 0,
    },
    progressFill: { height: 4, backgroundColor: colors.primary },
    downloadBtn: {
      width: 36,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radii.pill,
      backgroundColor: colors.primaryGlow,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
      marginTop: 2,
      flexShrink: 0,
    },
    downloadBtnActive: {},
    downloadBtnDisabled: { opacity: 0.6 },
    downloadBtnPressed: { opacity: 0.8 },
    apiFootnote: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      marginTop: 16,
      paddingTop: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    apiFootnoteBody: { flex: 1, minWidth: 0 },
    apiFootnoteText: {
      color: colors.textDim,
      fontSize: 12,
      lineHeight: 17,
    },
    loadMoreBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      marginTop: 12,
      paddingVertical: 12,
      borderRadius: radii.pill,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
      backgroundColor: colors.primaryGlow,
    },
    loadMoreBtnPressed: { opacity: 0.8 },
    loadMoreBtnDisabled: { opacity: 0.5 },
    loadMoreBtnText: {
      color: colors.primaryLight,
      fontSize: 14,
      fontWeight: "600",
    },
    detailCard: {
      maxHeight: "82%",
      paddingBottom: 12,
      paddingTop: 8,
    },
    detailHandle: {
      alignSelf: "center",
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.borderStrong,
      marginBottom: 14,
    },
    detailHero: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginBottom: 10,
    },
    detailHeroIcon: {
      width: 48,
      height: 48,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radii.md,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      flexShrink: 0,
    },
    detailHeroBody: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    detailTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 23,
    },
    detailPublisher: {
      color: colors.textDim,
      fontSize: 13,
      lineHeight: 17,
    },
    detailBlurb: {
      marginTop: 10,
      padding: 10,
      borderRadius: radii.sm,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    detailDescription: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 19,
    },
    detailSpecGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 12,
    },
    detailSpecCell: {
      width: "47%",
      flexGrow: 1,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: radii.sm,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      gap: 2,
    },
    detailSpecLabel: {
      color: colors.textDim,
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    detailSpecValue: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "600",
      lineHeight: 17,
    },
    detailCopyBlock: {
      marginTop: 12,
      gap: 4,
    },
    detailFieldLabel: {
      color: colors.textDim,
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    detailCopyPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 9,
      paddingHorizontal: 10,
      borderRadius: radii.sm,
      backgroundColor: colors.surfaceHover,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    detailCopyPillText: {
      flex: 1,
      color: colors.textMuted,
      fontSize: 11,
      lineHeight: 16,
      fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    },
    detailActions: {
      flexDirection: "row",
      gap: 10,
      marginTop: 14,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    detailCloseBtn: {
      flex: 1,
    },
    detailDownloadBtn: {
      flex: 1.2,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
  });
}
