import { StyleSheet } from "react-native";
import { radii, ThemeColors } from "../lib/theme";
import { createSectionSubtitleStyle } from "./SectionHintLines";

export function createListStyles(colors: ThemeColors) {
  return StyleSheet.create({
    listRoot: {
      flex: 1,
      width: "100%",
      alignSelf: "stretch",
    },
    listScroll: {
      flex: 1,
    },
    listEmbeddedRoot: {
      width: "100%",
      alignSelf: "stretch",
    },
    listEmbeddedContent: {
      width: "100%",
      alignSelf: "stretch",
    },
    searchWrap: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginHorizontal: 16,
      marginTop: 8,
      marginBottom: 12,
      paddingHorizontal: 14,
      paddingVertical: 11,
      backgroundColor: colors.surface,
      borderRadius: radii.pill,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      color: colors.inputText,
      fontSize: 15,
      padding: 0,
    },
    center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 32 },
    embeddedCenter: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 40,
      paddingHorizontal: 32,
    },
    emptyIcon: {
      width: 64,
      height: 64,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 16,
    },
    emptyTitle: { color: colors.text, fontSize: 17, fontWeight: "600", marginBottom: 8 },
    centerText: { color: colors.textMuted, fontSize: 14, lineHeight: 20 },
    retryBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 20,
      backgroundColor: colors.primaryGlow,
      paddingHorizontal: 20,
      paddingVertical: 11,
      borderRadius: radii.md,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
    },
    retryText: { color: colors.primaryLight, fontWeight: "600", fontSize: 14 },
    toggleWrap: { paddingTop: 6, paddingBottom: 2 },
    toggleBtn: {
      marginHorizontal: 0,
      marginBottom: 12,
      borderRadius: radii.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    toggleBtnPressed: { opacity: 0.85 },
    toggleBtnText: { color: colors.textMuted, fontWeight: "700", fontSize: 13 },
    pickerEmpty: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 32,
      paddingHorizontal: 16,
      gap: 8,
      marginBottom: 8,
    },
    openLibraryBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      marginTop: 12,
      paddingVertical: 14,
      borderRadius: radii.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    openLibraryBtnPressed: { opacity: 0.75 },
    openLibraryBtnText: { color: colors.textMuted, fontSize: 14, fontWeight: "600" },
  });
}

export function createRowStyles(colors: ThemeColors) {
  return StyleSheet.create({
    wrap: {
      marginBottom: 2,
    },
    container: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
    selected: {
      backgroundColor: colors.primaryGlow,
      borderRadius: radii.sm,
    },
    loading: { opacity: 0.55 },
    pressed: { opacity: 0.75 },
    mainPress: {
      flex: 1,
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
      minWidth: 0,
    },
    rowActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginTop: 2,
      flexShrink: 0,
    },
    actionBtn: {
      width: 32,
      height: 32,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radii.sm,
    },
    actionBtnDisabled: { opacity: 0.45 },
    actionBtnPressed: { opacity: 0.7 },
    modelIcon: {
      width: 44,
      height: 44,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      marginTop: 1,
    },
    left: { flex: 1, minWidth: 0 },
    titleRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: 6,
      marginBottom: 4,
    },
    name: { color: colors.text, fontSize: 17, fontWeight: "700", lineHeight: 22, flexShrink: 1 },
    nameSelected: { color: colors.primaryLight },
    stats: { color: colors.textMuted, fontSize: 11, lineHeight: 15 },
    loadLine: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginLeft: 56,
      marginTop: 2,
      marginBottom: 6,
      paddingRight: 4,
    },
    loadLineText: {
      flex: 1,
      minWidth: 0,
      color: colors.primaryLight,
      fontSize: 12,
      fontWeight: "500",
    },
    loadLineError: {
      marginLeft: 56,
      marginTop: 2,
      marginBottom: 6,
      paddingRight: 4,
      color: colors.error,
      fontSize: 12,
    },
    libraryWrap: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    libraryRow: {
      position: "relative",
      overflow: "hidden",
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
    libraryRowContent: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      zIndex: 1,
    },
    libraryRowSelected: {
      backgroundColor: colors.primaryGlow,
      borderRadius: radii.sm,
    },
    libraryIcon: {
      width: 44,
      height: 44,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    libraryBody: { flex: 1, minWidth: 0 },
    libraryName: {
      color: colors.text,
      fontSize: 17,
      fontWeight: "700",
      lineHeight: 22,
      flexShrink: 1,
    },
    libraryLoadLine: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginLeft: 54,
      marginTop: -4,
      marginBottom: 6,
      paddingRight: 4,
    },
    libraryLoadError: {
      marginLeft: 54,
      marginTop: -4,
      marginBottom: 6,
      paddingRight: 4,
      color: colors.error,
      fontSize: 12,
    },
    catalogRowWrap: {
      marginBottom: 2,
    },
    catalogRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
      paddingVertical: 10,
    },
    catalogRowError: {
      marginTop: -4,
      marginBottom: 4,
    },
    catalogProgressTrack: {
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.borderStrong,
      overflow: "hidden",
      marginTop: 6,
    },
    catalogProgressFill: {
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.primary,
    },
    catalogIcon: {
      width: 44,
      height: 44,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      marginTop: 1,
      position: "relative",
    },
    catalogBody: { flex: 1, minWidth: 0 },
    catalogDownloadBtn: {
      width: 36,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 999,
      backgroundColor: colors.primaryGlow,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
      marginTop: 2,
      flexShrink: 0,
    },
    catalogDownloadBtnDisabled: { opacity: 0.6 },
    catalogDownloadBtnActive: { opacity: 0.85 },
    catalogDownloadBtnPressed: { opacity: 0.8 },
  });
}

export function createLibrarySectionStyles(colors: ThemeColors) {
  return StyleSheet.create({
    sectionBlock: { marginBottom: 8 },
    sectionSpaced: { marginTop: 8 },
    sectionTitle: createSectionSubtitleStyle(colors),
  });
}

export function createSectionStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingTop: 14,
      paddingBottom: 8,
    },
    title: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    line: {
      flex: 1,
      height: 1,
    },
  });
}
