import { StyleSheet } from "react-native";
import { createPageTitleStyle } from "./typography";
import { radii, spacing, ThemeColors } from "./theme";

/** Shared modal / sheet / dialog styles aligned with app theme. */
export function createModalTheme(colors: ThemeColors) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      alignItems: "center",
      justifyContent: "center",
      padding: spacing.xl,
    },
    card: {
      width: "100%",
      maxWidth: 340,
      backgroundColor: colors.bgElevated,
      borderRadius: radii.xl,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      padding: spacing.xxl,
      paddingTop: spacing.xl + 4,
    },
    dialogIcon: {
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing.md,
      alignSelf: "center",
    },
    dialogTitle: {
      color: colors.text,
      fontSize: 17,
      fontWeight: "600",
      textAlign: "center",
      marginBottom: spacing.xs,
      letterSpacing: -0.2,
    },
    dialogMessage: {
      color: colors.textMuted,
      fontSize: 14,
      lineHeight: 20,
      textAlign: "center",
      marginBottom: spacing.lg,
    },
    dialogHint: {
      color: colors.textDim,
      fontSize: 14,
      lineHeight: 20,
      textAlign: "center",
      marginBottom: spacing.lg,
    },
    actionRow: {
      flexDirection: "row",
      gap: spacing.sm,
      marginTop: spacing.xs,
    },
    secondaryBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: radii.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: "center",
    },
    secondaryBtnText: {
      color: colors.textMuted,
      fontSize: 15,
      fontWeight: "600",
    },
    primaryBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: radii.md,
      backgroundColor: colors.primary,
      alignItems: "center",
    },
    primaryBtnText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "600",
    },
    destructiveBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: radii.md,
      backgroundColor: colors.error,
      alignItems: "center",
    },
    destructiveBtnText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "600",
    },

    sheetOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlayLight,
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: colors.bgElevated,
      borderTopLeftRadius: radii.xl,
      borderTopRightRadius: radii.xl,
      borderWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: 0,
      borderColor: colors.border,
      paddingTop: 10,
      paddingHorizontal: spacing.md,
    },
    sheetHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.borderStrong,
      alignSelf: "center",
      marginBottom: spacing.md,
    },
    sheetGroup: {
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      overflow: "hidden",
      marginBottom: spacing.sm,
    },
    sheetItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.md,
      paddingVertical: 14,
      paddingHorizontal: spacing.md,
    },
    sheetItemIcon: {
      width: 36,
      height: 36,
      borderRadius: radii.sm,
      backgroundColor: colors.surfaceHover,
      alignItems: "center",
      justifyContent: "center",
    },
    sheetItemText: { color: colors.text, fontSize: 16, flex: 1, fontWeight: "500" },
    sheetItemDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginLeft: 36 + spacing.md + spacing.md,
    },
    sheetCancel: {
      paddingVertical: 16,
      alignItems: "center",
      marginTop: spacing.xs,
    },
    sheetCancelText: { color: colors.textMuted, fontSize: 16, fontWeight: "500" },

    sheetOverlayRoot: {
      flex: 1,
      backgroundColor: "transparent",
    },
    pageContainer: { flex: 1, backgroundColor: colors.bgElevated },
    pageHandleWrap: { alignItems: "center", paddingTop: 8, paddingBottom: 2 },
    pageHandle: {
      width: 36,
      height: 5,
      borderRadius: 2.5,
      backgroundColor: colors.textDim,
    },
    pageHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.md,
    },
    pageHeaderBtn: { width: 36, alignItems: "center", justifyContent: "center" },
    pageTitle: createPageTitleStyle(colors),
    closeCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
  });
}
